### ISSUE TITLE
k not estimated, F too large

### ISSUE THREAD

**Issue by melisaolave** [esrud/currentNe#1]
Hi, thanks for making this available to the community!

I tried running currentNe in my dataset with 22 chromosomes, 1,517,015 SNPs, 16 individuals. I wanted the program to estimate the full siblings from the data, but it returned: 
Number of full siblings that a random individuals has in the sample:
Not estimated because F value is too large

and returned this about F:
Estimated F value of the population (deviation from H-W proportions):
-0.23442383

Estimated pop size is far to small, with Ne = 18. It makes no sense.

F value (inbreeding coefficient, right?) might be high, but still seems normal to me, and it is comprable to other closely related species. Why is not possible to estimate the number of full siblings? is there anything I can do?

thanks!
Melisa

**Comment by esrud** [comment]
There are many more heterozygotes in your sample than expected under the assumption of a single random mating population. In this situation, the sibling identification method implemented in currentNe is not reliable. However, the k-value can be estimated using other published methods (e.g. Jones & Wang 2010 MER).

Best,
Enrique

**Comment by melisaolave** [comment]
Hi Enrique,

thanks for your response. So, I suppose that the estimate of Ne is also not reliable wiht currentNe?

all the best,

Melisa

**Comment by esrud** [comment]
There are several factors that affect Ne estimates (see figures S2 and S3 in the supplementary material of the currentNe paper). If you think they are not involved in your case, then the Ne estimate might be fine, even though it assumes k=0 unless you provide a different value of k obtained by some other method.

Best,
Enrique

**Comment by ckopke** [comment]
Closing this issue as it seems already resolved. Feel free to open a new one in case this is not so
